# Generated by Django 2.2.28 on 2025-03-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Attack',
        ),
        migrations.AddField(
            model_name='enemy',
            name='defense',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='enemy',
            name='gold_drop',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='enemy',
            name='max_damage',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='enemy',
            name='max_health',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='enemy',
            name='min_damage',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='enemy',
            name='name',
            field=models.CharField(default='rabbit', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='max_score',
            field=models.IntegerField(default=0),
        ),
    ]
