# Generated by Django 2.2.28 on 2025-03-25 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20250320_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='agility',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='character',
            name='attack',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='current_health',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='character',
            name='defense',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='gold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='max_health',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='character',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rango.UserProfile'),
        ),
    ]
