# Generated by Django 2.2.28 on 2025-03-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_auto_20250325_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='image_filename',
            field=models.CharField(default='skeleton.jpg', max_length=100),
        ),
    ]
