# Generated by Django 2.2.28 on 2025-03-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_enemy_image_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='payed_stranger',
            field=models.BooleanField(default=False),
        ),
    ]
