# Generated by Django 2.2.28 on 2025-03-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_character_payed_stranger'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('attack', 'Attack'), ('buff', 'Buff')], default='attack', max_length=10),
        ),
        migrations.AddField(
            model_name='action',
            name='adp_increase',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='action',
            name='atk_increase',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='action',
            name='crit_chance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='action',
            name='def_increase',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='action',
            name='dmg_multiplier',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='action',
            name='luck_increase',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='action',
            name='miss_chance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='action',
            name='name',
            field=models.CharField(default='bash', max_length=50),
        ),
    ]
