# Generated by Django 2.2.28 on 2025-03-27 23:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0006_auto_20250327_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
