# Generated by Django 2.2.28 on 2025-03-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0009_leaderboardentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='boss_kills',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_boss_kills',
            field=models.IntegerField(default=0),
        ),
    ]
