# Generated by Django 2.2.28 on 2025-03-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0010_auto_20250328_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='total_kills',
            field=models.IntegerField(default=0),
        ),
    ]
