# Generated by Django 2.2.28 on 2025-03-28 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0011_userprofile_total_kills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='character',
        ),
        migrations.AddField(
            model_name='achievement',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rango.UserProfile'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
