# Generated by Django 2.2.28 on 2025-03-31 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0013_auto_20250331_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='agility',
            field=models.IntegerField(default=10),
        ),
    ]
